version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: nest_excel_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_excel_db
    ports:
      - "2345:2345"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
